### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by shupac** [rchl/IndentToParenthesis#1]
Hi, can you provide install instructions for sublime 3?

Thanks

**Comment by rchl** [comment]
I have now created a [pull request](https://github.com/wbond/package_control_channel/pull/6092) to add it to Package Control. It's probably best for you to wait for that to be approved and install it using Package Control.

Otherwise you could clone the repo manually into your Packages folder.

**Comment by shupac** [comment]
Great! Thank you! I'll wait for the Package Control update

**Comment by math2001** [comment]
You can do this:

1. Open up the command palette (`ctrl+shift+p`), and find `Package Control: Add Repository`. Then enter the URL of this repo: `https://github.com/rchl/IndentToParenthesis/` in the input field.
2. Open up the command palette again and find `Package Control: Install Package`, and just search for `IndentToParenthesis`. (just a normal install)

**Comment by shupac** [comment]
Thanks guys.

It didn't do what I needed but I appreciate the help. I might need to
develop my own plugin.

Side note, after I uninstalled the package, it seems like the modified
indentation behavior persisted. Any ideas?

**Comment by rchl** [comment]
If the package was truly removed then check also that the `indent_to_bracket` setting is disabled. This is the setting for built-in functionality that does similar thing.

**Comment by shupac** [comment]
Yes, that was it. Thanks
